# Generated by Django 3.1.2 on 2020-10-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_class', models.CharField(max_length=30)),
                ('s_dob', models.DateField(null=True)),
                ('s_address', models.CharField(max_length=50)),
                ('s_phonenum', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_degree', models.CharField(max_length=10)),
                ('t_lastedu', models.CharField(max_length=30)),
                ('t_dob', models.DateField(null=True)),
                ('t_address', models.CharField(max_length=50)),
                ('t_phonenum', models.CharField(max_length=20)),
                ('t_email', models.CharField(max_length=30)),
            ],
        ),
    ]
