# Generated by Django 3.1.2 on 2020-10-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='t_lastedu',
            new_name='t_subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='t_degree',
        ),
        migrations.AlterField(
            model_name='student',
            name='s_class',
            field=models.CharField(max_length=10),
        ),
    ]
